### ISSUE TITLE
get an error when triggle github actions 

### ISSUE THREAD

**Issue by eiuapp** [mattbailey/actions-hugo#1]
when i set the github actions

```yml
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build
      uses: mattbailey/actions-hugo@v0.57.2
      if: github.event.deleted == false
      with:
        args: --gc --minify
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN_MATTBAILEY }}
```

get the error:

``` 
Building sites … WARN 2019/09/09 08:14:01 In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.
WARN 2019/09/09 08:14:01 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}

                   | EN  
+------------------+----+
   Pages            | 23  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 80  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 58 ms
Setting up git
cloning
error: unknown option `---END'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
```

what's my problem?
